hirosystems/token-metadata-api

src/token-processor/queue/job-queue.ts
tests/job-queue.test.ts

fix: queue graceful shutdown

---

migrations/1670264425574_smart-contracts.ts
migrations/1670265062169_tokens.ts
src/api/init.ts
src/api/routes/nft.ts
src/api/routes/sft.ts
src/api/types.ts
src/index.ts
src/pg/blockchain-api/pg-blockchain-api-store.ts
src/pg/pg-store.ts
src/pg/types.ts
src/token-processor/blockchain-api/blockchain-smart-contract-monitor.ts
src/token-processor/queue/job-queue.ts
src/token-processor/queue/job/process-smart-contract-job.ts
src/token-processor/queue/job/process-token-job.ts
src/token-processor/util/metadata-helpers.ts
src/token-processor/util/sip-validation.ts
tests/blockchain-smart-contract-monitor.test.ts
tests/ft.test.ts
tests/job-queue.test.ts
tests/metadata-helpers.test.ts
tests/nft.test.ts
tests/process-smart-contract-job.test.ts
tests/process-token-job.test.ts
tests/sft.test.ts
tests/status.test.ts

* Detect and process SFT contracts
* Scan API `contract_logs` table to look for SFT mints when processing contract (SIP-013 contracts don't have a direct way to get this information)
* Detect SFT mints through blockchain monitor and enqueue tokens for processing
* Add SFT endpoints to consume metadata
Fixes #56

feat: add SIP-013 SFT support

---

package-lock.json
src/pg/postgres-tools/errors.ts
src/token-processor/blockchain-api/blockchain-smart-contract-monitor.ts
src/token-processor/queue/job-queue.ts
src/token-processor/queue/job/job.ts
src/token-processor/queue/job/process-smart-contract-job.ts
src/token-processor/queue/job/process-token-job.ts
tests/job-queue.test.ts
tests/job.test.ts

* Recover gracefully from pg disconnections by clearing failed jobs from queue and letting the queue loop try again for a connection indefinitely
* Remove long-running pg transactions that encompassed the entire token/contract job processing (including metadata fetch). Now, transactions are opened and closed only when required which improves connection reuse on the entire service.
Related to #82

fix: handle pg disconnections and transaction management

---

Dockerfile
README.md
migrations/1670264425574_smart-contracts.ts
migrations/1670265062169_tokens.ts
migrations/1670266371036_jobs.ts
migrations/1675368570737_rate-limited-hosts.ts
package-lock.json
src/env.ts
src/pg/pg-store.ts
src/pg/types.ts
src/token-processor/queue/job/process-token-job.ts
src/token-processor/util/errors.ts
src/token-processor/util/helpers.ts
src/token-processor/util/metadata-helpers.ts
tests/process-token-job.test.ts

* Save domains that respond with 429 status codes
* Parse the `Retry-After` header and save that date for retries, default to 1 hour if not specified
* Change all `timestamp` columns to `timestamptz` to correctly use and compare pg timestamps
* Upgrade undici to include new error types from https://github.com/nodejs/undici/pull/1888
Fixes #86

feat: throttle requests to rate limited domains

---

src/api/util/cache.ts
src/pg/pg-store.ts
tests/cache.test.ts

Also, add tests for FT, NFT and SFT endpoint cache responses

fix: etag cache calculation with url prefix

---

src/api/routes/ft.ts
src/api/schemas.ts
src/pg/pg-store.ts
src/pg/types.ts
tests/ft.test.ts

This PR makes the FT response be backwards-compatible to the current Stacks API FT response, so we can set up a simple redirect/rewrite from there to this new API immediately.
Example old Stacks API FT response:
```json
{
"token_uri": "https://heystack.xyz/token-metadata.json",
"name": "Heystack",
"description": "Heystack is a SIP-010-compliant fungible token on the Stacks Blockchain, used on the Heystack app",
"image_uri": "https://heystack.xyz/assets/Stacks128w.png",
"image_canonical_uri": "https://heystack.xyz/assets/Stacks128w.png",
"tx_id": "0xef2ac1126e16f46843228b1dk4830e19eb7599129e4jf392cab9e65ae83a45c0",
"sender_address": "ST399W7Z9WS0GMSNQGJGME5JAENKN56D65VGMGKGA",
"symbol": "HEY",
"decimals": 5
}
```
New FT response: https://token-metadata-csgxi67fv-blockstack.vercel.app/#tag/T …

fix: return FT metadata in a backwards compatible way

---

src/token-processor/stacks-node/stacks-node-rpc-client.ts
tests/stacks-node-rpc-client.test.ts

A few contracts are creating an infinite loop of retries because some of their functions don't conform to SIP-010. For example, `SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.token-wxusd` returns this for `get-total-supply` which according to SIP-010 should always be `uint`.
```clarity
;; @desc get-total-supply
;; @returns (response uint)
(define-read-only (get-total-supply)
;; least authority Issue D
ERR-NOT-SUPPORTED
)
```
For now, this PR avoids retrying indefinitely in these cases. In the future we could relax these restrictions and mark those fields as `undefined`

fix: do not retry incorrect clarity values

---

migrations/1679941023060_add-invalid-job-status.ts
src/api/schemas.ts
src/api/util/errors.ts
src/pg/errors.ts
src/pg/pg-store.ts
src/pg/types.ts
src/token-processor/queue/job/job.ts
src/token-processor/stacks-node/stacks-node-rpc-client.ts
src/token-processor/util/errors.ts
src/token-processor/util/metadata-helpers.ts
src/token-processor/util/types.ts
tests/ft.test.ts
tests/job.test.ts
tests/metadata-helpers.test.ts
tests/nft.test.ts
tests/sft.test.ts
tests/stacks-node-rpc-client.test.ts

* Add `invalid` job status
* Mark invalid when there is a user error (wrong metadata format, not SIP-016, unreachable, bad clarity types, etc.)
* Respond with an informative error if invalid contracts/tokens are requested
Fixes #128 
Fixes #118
Fixes #138

feat: add `invalid` job status to mark invalid contracts or tokens

---

migrations/1686538772911_ft-list-indices.ts
src/api/routes/ft.ts
src/api/schemas.ts
src/pg/pg-store.ts
src/pg/types.ts
tests/ft.test.ts

Creates a new endpoint `/metadata/ft` which:
* Lists all fungible tokens with valid metadata
* Results include basic metadata, not detailed metadata
* Filters by `name` (LIKE match) or `symbol`
* Orders results by `name` or `symbol`
Fixes #161

feat: add endpoint to list all FTs

---

src/api/routes/ft.ts
src/api/schemas.ts
src/pg/pg-store.ts
tests/ft.test.ts

Adds the `contract_principal` value to FT index responses. Also, fixes bug when filtering for name or symbol had no matches.
```json
{
"decimals": 6,
"description": "StackSwap Project",
"image_canonical_uri": "https://app.stackswap.org/icon/stsw.svg",
"image_uri": "https://app.stackswap.org/icon/stsw.svg",
"name": "STACKSWAP",
"sender_address": "SP1Z92MPDQEWZXW36VX71Q25HKF5K2EPCJ304F275",
"symbol": "STSW",
"token_uri": "https://app.stackswap.org/token/stsw.json",
"total_supply": "1000000000000000",
"tx_id": "0x3edffbd025ca2c29cfde8c583c0e0babacd4aa21075d10307d37c64ae78d579e",
"contract_principal": "SP1Z92MPDQEWZXW36VX71Q25HKF5K2EPCJ304F275.stsw-token-v4a",
}
```
---

feat: add contract principal to ft index responses

---

src/pg/pg-store.ts
tests/ft.test.ts

Makes the FT search on `name` and `symbol` case insensitive.
No
`/metadata/ft?symbol=mia`
---

feat: make FT search on name and symbol case insensitive

---

.github/workflows/vercel.yml

Closes https://github.com/hirosystems/ordinals-api/issues/103
Related: https://github.com/hirosystems/stacks-blockchain-api/pull/1787
A deploy hook in Vercel will be contacted whenever there's an update to the `master` branch in this repo, which should automate changes to the docs site as docs changes are made here.

docs: trigger docs.hiro.so refresh on commits to master

---

src/admin-rpc/init.ts
src/pg/pg-store.ts
src/token-processor/util/image-cache.ts
tests/admin-rpc.test.ts
tests/helpers.ts

feat: add admin rpc to reprocess token image cache

---

src/token-processor/util/metadata-helpers.ts
src/token-processor/util/types.ts
tests/process-token-job.test.ts

Also accept other non-compliant image fields `image_uri` and `image_canonical_uri`

fix: handle missing image uris

---

package-lock.json
package.json
src/admin-rpc/init.ts
src/api/@types/fastify/index.d.ts
src/env.ts
src/index.ts
src/token-processor/images/image-cache.ts
src/token-processor/queue/job-queue.ts
src/token-processor/util/metadata-helpers.ts
tests/admin/admin-rpc.test.ts
tests/token-queue/job-queue.test.ts

Also:
* Add profiler server
* Add option to turn queue automatic start on/off

fix: process image cache in stages for memory optimization

---

src/token-processor/images/image-cache.ts

Optimizes for memory when dealing with GIFs. Related to #219

fix: take only first page of gif images

---

src/env.ts
src/token-processor/queue/job/job.ts

Sets and enforces a maximum execution time for individual jobs.
Fixes #243

fix: set maximum job timeout

---

src/token-processor/images/image-cache.ts
src/token-processor/util/metadata-helpers.ts
tests/token-queue/metadata-helpers.test.ts

Marks a retryable error when the connection to the metadata server was successful but then interrupted.
Fixes #242

fix: catch econnreset errors

---

src/api/routes/status.ts
src/api/schemas.ts
src/pg/chainhook/chainhook-pg-store.ts
src/token-processor/token-processor-metrics.ts
tests/api/status.test.ts

For easier API status monitoring

fix: add block_height to status and prometheus

---

src/api/routes/ft.ts
src/api/routes/status.ts
src/api/schemas.ts
src/api/util/cache.ts
tests/api/cache.test.ts

Creates a chain tip cache handler that advances with the Stacks block height. Adds it to `/metadata` and `/metadata/ft` endpoints. Also reuses some of the functions already migrated to the API toolkit.
Fixes #254

fix: add chain tip etag generator

---

src/token-processor/stacks-node/stacks-node-rpc-client.ts
tests/token-queue/process-token-job.test.ts
tests/token-queue/stacks-node-rpc-client.test.ts

When detecting a new contract or token via chainhook, we do a read-only call to that contract in the Stacks node immediately to get the token's data. However, if that contract is not yet ready for read on the node (`NoSuchContract` error), we need to try again later.

fix: retry when a contract is not yet found

---

migrations/1725039927416_job-retry-after.ts
src/env.ts
src/pg/pg-store.ts
src/pg/types.ts
src/token-processor/queue/job/job.ts
src/token-processor/queue/job/process-token-job.ts
tests/token-queue/job.test.ts
tests/token-queue/process-token-job.test.ts

Also, set a customized job retry delay when receiving a rate limit from a metadata host, so we don't enqueue the same job again if we're expecting to still be rate limited.
Fixes #84

feat: add configurable delay for retrying jobs

---

src/pg/pg-store.ts
src/token-processor/util/metadata-helpers.ts
tests/api/nft.test.ts
tests/token-queue/metadata-helpers.test.ts
tests/token-queue/process-token-job.test.ts

Fixes an error that prevented boolean properties from being saved
```
PostgresError: column "value" is of type jsonb but expression is of type boolean
at ErrorResponse (/app/node_modules/postgres/cjs/src/connection.js:771:26)
at handle (/app/node_modules/postgres/cjs/src/connection.js:473:6)
at Socket.data (/app/node_modules/postgres/cjs/src/connection.js:314:9)
at Socket.emit (node:events:519:28)
at addChunk (node:internal/streams/readable:559:12)
at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
at Readable.push (node:internal/streams/readable:390:5)
at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
at cachedError (/app/node_modules/postgres/cjs/src/query.js:171:23)
at new Query …
```

fix: allow boolean metadata properties

---

src/api/util/helpers.ts
src/pg/chainhook/chainhook-pg-store.ts
tests/api/nft.test.ts
tests/api/status.test.ts
tests/chainhook/chainhook-observer.test.ts

So we don't miss subsequent apply blocks in the same block message

fix: handle updated chain tip on rollbacks correctly

---

src/pg/chainhook/block-cache.ts
tests/chainhook/smart-contracts.test.ts
tests/helpers.ts

Do not process any events from failed Stacks transactions.
Fixes #262

fix: ignore events from failed transactions

---

src/token-processor/util/metadata-helpers.ts
tests/token-queue/metadata-helpers.test.ts
tests/token-queue/process-token-job.test.ts

We previously ignored JSON metadata that was not SIP-016 compliant (without a `name` value at least) and processed the token silently, but this is an incorrect approach. This PR changes that so it fails and marks the token as `invalid`.

fix: treat non-compliant SIP-016 metadata as invalid

---

.github/workflows/ci.yml
src/env.ts

To get new alerts working the prometheus port needs to be fixed. https://github.com/hirosystems/devops/issues/1785
This issue looks to have been introduced on this commit --> https://github.com/hirosystems/token-metadata-api/commit/c769d2950d65448265caf2bf6bd78fce437358c0
NA

Fix metrics default port for prometheus

---

src/pg/chainhook/chainhook-pg-store.ts
tests/chainhook/sft-events.test.ts

Allows multiple SFT mints per tx for the same token. Fixes the error:
```
ON CONFLICT DO UPDATE command cannot affect row a second time
```

fix: allow multiple sft mints for the same token per transaction

---

src/pg/chainhook/chainhook-pg-store.ts

This change makes sure the Etag for this token gets updated so supply changes can be reflected to clients properly

fix: update ft date on supply change

---

package-lock.json
package.json
src/chainhook/server.ts
tests/helpers.ts

If a chainhook predicate goes obsolete, update its starting block height on re-registration.
There is a bug on chainhook which sometimes marks active predicates as inactive, forcing the Metadata API to re-register so it receives blocks again. However, since we weren't updating the re-registration starting block height, we ended up in an infinite loop that made us receive blocks from the last block height seen on boot. This caused the API to fall significantly behind chain tip.

fix: update chainhook predicate start_block upon re-registration

---

src/env.ts
src/token-processor/images/image-cache.ts
src/token-processor/queue/job/process-token-job.ts
src/token-processor/util/metadata-helpers.ts
tests/token-queue/metadata-helpers.test.ts

If a token metadata URI comes with a hard coded IPFS gateway (like `https://ipfs.io/ipfs/...`), replace it with our configured value for `ENV.PUBLIC_GATEWAY_IPFS`. This makes sure we can handle cases where our cloud servers get rate limited or black listed by gateways.

fix: replace hard coded IPFS gateways with configurable gateway
