hirosystems/token-metadata-api

.vscode/launch.json
.vscode/tasks.json
docker/docker-compose.dev.postgres.yml
package.json
src/pg/pg-store.ts
src/token-processor/blockchain-api/blockchain-importer.ts
tests/nft.test.ts

feat: launch postgres on docker for test suite

---

src/token-processor/util/metadata-helpers.ts
tests/metadata-helpers.test.ts

feat: check raw metadata JSON types with typebox

---

.vscode/launch.json
src/api/routes/status.ts
tests/helpers.ts
tests/metadata-helpers.test.ts
tests/status.test.ts

feat: expand status endpoint to include token, contract, job counts

---

src/pg/pg-store.ts
src/token-processor/queue/job-queue.ts
src/token-processor/queue/job.ts
tests/job-queue.test.ts

fix: handle pg errors on queue

---

.vscode/launch.json
migrations/00005-jobs.ts
src/api/init.ts
src/index.ts
src/pg/pg-store.ts
src/pg/postgres-tools/base-pg-store.ts
src/shutdown-handler.ts
src/token-processor/blockchain-api/blockchain-importer.ts
src/token-processor/queue/job-queue.ts
src/token-processor/queue/job.ts
src/token-processor/util/helpers.ts

feat: add graceful shutdown

---

src/api/routes/ft.ts
src/api/routes/nft.ts
src/api/types.ts
src/api/util/cache.ts
src/api/util/errors.ts
src/index.ts
src/pg/errors.ts
src/pg/pg-store.ts
tests/ft.test.ts
tests/nft.test.ts

feat: return token error responses for different scenarios

---

src/token-processor/util/metadata-helpers.ts
tests/metadata-helpers.test.ts

feat: support arweave URIs

---

src/token-processor/util/metadata-helpers.ts
tests/metadata-helpers.test.ts

feat: allow other keys for token ids and image uris

---

src/index.ts
src/pg/blockchain-api/pg-blockchain-api-store.ts
src/pg/pg-store.ts
src/token-processor/blockchain-api/blockchain-importer.ts
src/token-processor/blockchain-api/blockchain-smart-contract-monitor.ts
src/token-processor/util/sip-validation.ts
tests/blockchain-smart-contract-monitor.test.ts
tests/sip-validation.test.ts

feat: support SIP-019 notifications

---

migrations/00001-tokens.ts
src/api/routes/ft.ts
src/pg/pg-store.ts
src/pg/types.ts
src/token-processor/blockchain-api/blockchain-importer.ts
src/token-processor/process-token-job.ts
tests/ft.test.ts
tests/process-token-job.test.ts

fix: change total supply column type to `numeric`

---

src/env.ts
src/token-processor/queue/job.ts
src/token-processor/util/metadata-helpers.ts
tests/metadata-helpers.test.ts

feat: add configurable storage gateways

---

src/index.ts
src/logger.ts
src/pg/postgres-tools/index.ts
src/shutdown-handler.ts
src/token-processor/blockchain-api/blockchain-importer.ts
src/token-processor/blockchain-api/blockchain-smart-contract-monitor.ts
src/token-processor/process-smart-contract-job.ts
src/token-processor/process-token-job.ts
src/token-processor/queue/job-queue.ts
src/token-processor/queue/job.ts

feat: add winston logger

---

src/api/util/cache.ts
src/env.ts
src/token-processor/process-smart-contract-job.ts
src/token-processor/queue/job.ts
src/token-processor/util/metadata-helpers.ts
tests/process-smart-contract-job.test.ts

feat: restrict max nft count per contract

---

migrations/1670265062169_tokens.ts
src/pg/pg-store.ts
src/pg/types.ts
src/token-processor/util/sip-validation.ts
tests/blockchain-smart-contract-monitor.test.ts
tests/sip-validation.test.ts

#7 
automatic dynamic refreshes still pending

feat: metadata update modes

---

src/token-processor/util/metadata-helpers.ts
tests/metadata-helpers.test.ts

fix: parse stringable values in raw metadata

---

.commitlintrc.json
.husky/commit-msg
package-lock.json
package.json

chore: add husky to enforce conventional commits

---

docs/feature-guides/token-meta-data-service.md

Added token metadata service to Docs. 
Pulled README content into docs.

docs: Token metadata service

---

package-lock.json
package.json
src/token-processor/util/metadata-helpers.ts
tests/metadata-helpers.test.ts

fix: support JSON5 metadata strings

---

src/token-processor/util/metadata-helpers.ts

fix: ignore invalid ssl certs for metadata fetch

---

src/env.ts
src/token-processor/util/metadata-helpers.ts
tests/metadata-helpers.test.ts

Max redirects configurable via ENV var

fix: follow redirects when fetching metadata

---

src/api/types.ts
src/api/util/helpers.ts
tests/ft.test.ts
tests/nft.test.ts
tests/sft.test.ts

fix: display cached image in metadata responses

---

docs/feature-guides/token-metadata-api.md

Reverted back to adding full links.

Added Git links to point to the right src and config files

---

jest.config.js
src/token-processor/queue/job/process-token-job.ts
tests/process-token-job.test.ts

fix: support FTs with missing metadata but correct token data

---

docs/feature-guides/rate-limiting.md

- Added rate limit for Metadata API.

Add rate-limit to Metadata API

---

.vscode/launch.json
src/api/init.ts
src/api/util/helpers.ts
src/index.ts
src/token-processor/token-processor-metrics.ts

fix: run prometheus on port 9153

---

.github/workflows/ci.yml
jest.config.js

build: add codecov

---

docs/overview.md

Added a note to include OpenAPI spec and Github source code links in the docs.
Fixes https://github.com/hirosystems/docs/issues/418

Updated overview page to use openapi and source code repo links

---

util/openapi-generator.ts

Related to https://github.com/hirosystems/docs/issues/426

docs: generate JSON openapi schema

---

src/api/schemas.ts

Add a link to the [main docs](https://docs.hiro.so/token-metadata-api) overview page from api reference page [here](https://docs.hiro.so/metadata)

update to new url path

---

src/token-processor/queue/job/process-token-job.ts
tests/process-token-job.test.ts

fix: accept FTs with incorrect return type for get-token-supply

---

src/token-processor/stacks-node/stacks-node-rpc-client.ts
tests/stacks-node-rpc-client.test.ts

fix: retry `NoSuchContract` clarity errors

---

package-lock.json
package.json
src/token-processor/images/image-cache.ts

fix: use google cloud library for image uploads

---

src/token-processor/images/image-cache.ts
tests/token-queue/image-cache.test.ts

feat: convert data: image uris into image files and upload to cdn

---

src/env.ts
src/index.ts

fix: force close db connection after a configurable timeout
